config/routes.rb
RailsStarter::Application.routes.draw do

  root :to => 'searches#query'
  match 'search/count' => 'searches#count_tweets', :as => :count_tweets

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/say_controller.rb
require 'json'

# Controller and action definition for uri say/hello
# See routing configuration in config/routes.rb
class SayController < ApplicationController
  def hello
    # get user ip from request
    @yourip = request.remote_ip

    # use params[:name] to get request parameter value by name
    # @parameter = params[:name]

    # get Ruby version and Rails version
    @ruby_version = RUBY_VERSION
    @rails_version = Rails::VERSION::STRING

    # environment variable 'VCAP_SERVICES' is in JSON format. You may use JSON.parse() to get Ruby hash
    # 'VCAP_SERVICES' is empty if your didn't bind any service to the application
    # @vcap_services = ENV['VCAP_SERVICES']
    # @home = ENV['HOME']
    # @memory_limit = ENV['MEMORY_LIMIT']
    # @port = ENV['PORT']
    # @pwd = ENV['PWD']
    # @tmpdir = ENV['TMPDIR']
    # @user = ENV['USER']
    # 'VCAP_APPLICATION' is in JSON format, use JSON.parse() to get Ruby hash
    # @vcap_app = JSON.parse(ENV['VCAP_APPLICATION'])

    # Variables Defined by Ruby Buildpack
    # @bundle_bin_path = ENV['BUNDLE_BIN_PATH']
    # @bundle_gemfile = ENV['BUNDLE_GEMFILE']
    # @bundle_without = ENV['BUNDLE_WITHOUT']
    # @database_url = ENV['DATABASE_URL']
    # @gem_home = ENV['GEM_HOME']
    # @rack_env = ENV['RACK_ENV']
    # @rails_env = ENV['RAILS_ENV']

    env = {}
    # loop to parse all JSON object
    # @env is available in the view: views/say/hello.html.erb
    ENV.each do |key, value|
        begin
            obj = JSON.parse(value)
            env[key] = JSON.pretty_generate(obj)
        rescue
            env[key] = value
        end
      end
    @env = env

  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def query    
  end

  def count_tweets
    query = params[:q]
    result = TwitterService.new.count_tweets(query)
    render json: { query: query, count: result}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IBM Insights for Twitter Demo App</title>
	<link rel="shortcut icon" href="https://cdetestapp.mybluemix.net/twitter_favicon.png">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/hello.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<TITLE>Ruby on Rails Starter Application</TITLE>
		<link href='/stylesheets/style.css' rel='stylesheet'>
	</HEAD>

	<BODY>
		  <table>
			<tr>
			  <td style='width:30%;'>
				<img class = 'newappIcon' src='assets/newapp-icon.png'>
			  </td>
			  <td>
				<h1>Hi there! <%= @env %></h1>
				<p class='description'></p>
				Thanks for creating a <span class = "blue">Ruby on Rails Starter Application</span>. Get started by reading our <a href = "https://www.ng.bluemix.net/docs/#starters/rails/index.html#rails">documentation</a> or use the Start Coding guide under your app in your dashboard.
			  </td>
			</tr>
		  </table>
	</BODY>
</HTML>

app/views/search/query.html.erb
<!DOCTYPE html>
<!-- saved from url=(0033)https://cdetestapp.mybluemix.net/ -->
<div style="width:100%;">
	<div class="display_logo">
		<img src="/assets/cdetestapp.png">
	</div>
	<div class="display_search_text">
		<input id="search_text" type="text" class="search_textbox" onkeydown="if (event.keyCode == 13) { searchEnter() }">
	</div>
	<div class="display_buttons">
		<!-- table required for safari windows -->
		<table>
			<tbody><tr>
				<td>
					<input id="search_button" type="button" value="Twitter Search" class="search_button" onclick="searchTweets(searchText())">
				</td>
				<td>
					<input type="button" value="Twitter Count" class="search_button" onclick="countTweets(searchText())">
				</td>
			</tr>
		</tbody></table>
	</div>
</div>

<div id="display_spinner" class="display_spinner">
</div>
<div style="width:100%;">
	<div id="display_query" class="display_query">
	</div>
	<div id="display_count" class="display_count">
	</div>
</div>
<div style="width:100%;">
	<div id="display_markup" class="center">
	</div>
</div>

<script type="text/javascript">
	var service_url = "<%= @service_url %>";
	var service_port = "<%= @service_port %>";
</script>

app/views/searches/query.html.erb
<!DOCTYPE html>
<!-- saved from url=(0033)https://cdetestapp.mybluemix.net/ -->
<div style="width:100%;">
	<div class="display_logo">
		<img src="/assets/cdetestapp.png">
	</div>
	<div class="display_search_text">
		<input id="search_text" type="text" class="search_textbox" onkeydown="if (event.keyCode == 13) { searchEnter() }">
	</div>
	<div class="display_buttons">
		<!-- table required for safari windows -->
		<table>
			<tbody><tr>
				<td>
					<input id="search_button" type="button" value="Twitter Search" class="search_button" onclick="searchTweets(searchText())">
				</td>
				<td>
					<input type="button" value="Twitter Count" class="search_button" onclick="countTweets(searchText())">
				</td>
			</tr>
		</tbody></table>
	</div>
</div>

<div id="display_spinner" class="display_spinner">
</div>
<div style="width:100%;">
	<div id="display_query" class="display_query">
	</div>
	<div id="display_count" class="display_count">
	</div>
</div>
<div style="width:100%;">
	<div id="display_markup" class="center">
	</div>
</div>

<script type="text/javascript">
	var count_tweets_url = "<%= count_tweets_path %>";
	// var service_url = "<%#= @service_url %>";
	// var service_port = "<%#= @service_port %>";
</script>